name: rehab_app_319
description: "復健訓練應用程式 - 協助用戶進行口腔和肢體復健訓練"
publish_to: 'none'

version: 2.0.0+18344

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  noise_meter: 5.0.2
  permission_handler: ^11.0.1 
  speech_to_text: ^6.1.1
  fftea: ^1.5.0+1
  flutter_localization: ^0.1.10
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  dropdown_button2: 2.0.0
  easy_debounce: 2.0.1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.2
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 6.0.0
  google_fonts: ^6.2.0
  intl: any
  json_path: 0.4.1
  mask_text_input_formatter: 2.4.0
  page_transition: 2.0.4
  provider: 6.0.4
  shared_preferences: 2.0.17
  shared_preferences_android: 2.1.0
  shared_preferences_foundation: 2.1.1
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: 2.1.0
  substring_highlight: 1.0.33
  timeago: 3.2.2
  url_launcher: 6.1.10
  audioplayers: ^5.0.0
  video_player: ^2.6.1
  image_picker: ^0.8.6
  camera: ^0.10.0+4
  path: ^1.8.2
  path_provider: ^2.1.4
  google_mlkit_pose_detection:
    path: lib/vision_detector_views/mlkit_api_source/google_mlkit_pose_detection
  google_mlkit_image_labeling:
    path: lib/vision_detector_views/mlkit_api_source/google_mlkit_image_labeling
  google_mlkit_face_detection:
    path: lib/vision_detector_views/mlkit_api_source/google_mlkit_face_detection
  flutter_screenutil: ^5.7.0
  workmanager: ^0.5.1
  flutter_local_notifications: ^14.0.0+2
  file_picker: ^5.2.10
  fl_chart: ^0.62.0
  pytorch_mobile: ^0.2.2
  image: ^4.5.4
  uuid: ^4.5.1
  onnxruntime: ^1.4.1
  record: ^4.4.4
  cupertino_icons: ^1.0.6
  firebase_core: ^2.12.0
  # 暫時註解掉 Firebase Messaging 以解決 Xcode 16 兼容性問題
  # firebase_messaging: ^14.6.0
  flutter_launcher_icons: 0.13.1
  complex: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/picture/a.png
    - assets/picture/b.png
    - assets/pose_audios/upper/
    - assets/pose_audios/lower/
    - assets/pose_audios/
    - assets/taigi_pose_audios/upper/
    - assets/taigi_pose_audios/lower/
    - assets/taigi_pose_audios/
    - assets/ml/
    - assets/model/rsst_integrated_2k2_cnn_att2_2_ir9.onnx
    - assets/model/rsst_v10_ir9.onnx

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appicon.jpg"

